### ISSUE TITLE
OyVey continued by pasting Phobos

### ISSUE THREAD

**Issue by RealzPrestige** [Notme11/Notorious2.0#1]

**Comment by Notme11** [comment]
lol

**Comment by ssllllll** [comment]
Same as mint lelel

**Comment by ZenovJB** [comment]
> Same as mint lelel

oyvey continued dev right here

**Comment by RealzPrestige** [comment]
> Same as mint lelel

Whats up oyvey continued dev 🧐

**Comment by ssllllll** [comment]
Ive made lot of things i just dont create public discords to flex im a skider, like mint devs make lel

**Comment by ProfKambing** [comment]
LMAO

**Comment by ProfKambing** [comment]
"Ive made lot of things" bro,,

**Comment by ssllllll** [comment]
Kambing was skidding europa shaderchams AND HE COULDNT PASTE EM LOL, CANT EVEN CTRL + C, CTRL + V,

**Comment by ProfKambing** [comment]
i was never skidding them 😂

**Comment by ssllllll** [comment]
![Screenshot_20211221-061059](https://user-images.githubusercontent.com/86989232/146921238-e7814548-e958-48cb-8b08-6d720d356a23.jpg)
![Screenshot_20211221-061452](https://user-images.githubusercontent.com/86989232/146921243-11e4755d-2f84-4ab8-87cb-5c48e37218f0.jpg)

**Comment by ProfKambing** [comment]
zprestige added it bro.. nice pooron phone tho

**Comment by ssllllll** [comment]
> zprestige added it bro.. nice pooron phone tho

zprestige skided it* 

My phone is ass same as mint lel

**Comment by ProfKambing** [comment]
pooron

**Comment by ssllllll** [comment]
Ur from malaysia so shut up dumbass

**Comment by ProfKambing** [comment]
atleast i dont live in slumps 😹

**Comment by master7720** [comment]
jesus guys go out side
